---
title: "04_plotting results"
author: "Joe Brown"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### weighted wamring

```{r}
gsat_ensemble <- do.call(rbind, gsat_data)
row.names(gsat_ensemble) <-  NULL

# Step 1: Calculate the total weight for each run
top_runs <- gsat_ensemble %>%
  group_by(run_number) %>%  # Group by run_number
  summarize(total_weight = sum(mc_weight), .groups = "drop") %>%  # Sum mc_weight for each run_number
  arrange(desc(total_weight)) %>%  # Sort by total weight in descending order
  slice_head(prop = 0.20) %>%  # Select the top 20% of runs based on total weight
  ungroup()  # Remove grouping

# Step 2: Filter the original dataset to include only the top 20% of runs by weight
top_runs_data <- gsat_ensemble %>%
  filter(run_number %in% top_runs$run_number)  

# median (CI) warming calculation
gsat_projection <- top_runs_data %>% 
  group_by(year, scenario) %>% 
  summarize(
    median = quantile(x = value, probs = 0.5), 
    ci_5 = quantile(x = value, probs = 0.05),
    ci_10 = quantile(x = value, probs = 0.10), 
    ci_90 = quantile(x = value, probs = 0.90), 
    ci_95 = quantile(x = value, probs = 0.95),
    ci_66 = quantile(x = value, probs = 0.66), 
    ci_33 = quantile(x = value, probs = 0.33)) 

```

```{r}
temp_projection_plot <- 
  ggplot(data = subset(gsat_projection, 
                       year > 1995)) +
  geom_ribbon(aes(x = year, 
                  ymin = ci_5, 
                  ymax = ci_95), 
              alpha = 0.3, 
              linetype = "blank", 
              color = "lightgrey") +
  geom_ribbon(aes(x = year, 
                  ymin = ci_33, 
                  ymax = ci_66),
              alpha = 0.5,
              fill = "orange") +
   geom_line(aes(x = year, 
                y = median), 
            linewidth = 0.5, 
            color = "black") +
  labs(x = "Year", 
       y = expression(paste("Future Warming (GSAT) relative to 1995-2014 (", degree, "C)"))) +
    facet_wrap(~scenario) +
  theme_light()

temp_projection_plot
ggsave("figures/temp_projection.png", 
       device = "png", 
       dpi = 300)
```